### PR TITLE
Re-organizing AOSC Wiki

### PR DESCRIPTION
**Pull request by bobby285271**
* Place all pages into section folders according to their previous file name.
* Rename section folders as follows:

| Before | After |
|:---|:---|
|`/content/dev` | `/content/developer` |
|`/content/dev/sys` | `/content/developer/system` |
|`/content/infra` | `/content/infrastructure` |
|`/content/infra/err` | `/content/infrastructure/errata` |
|`/content/infra/kb` | `/content/infrastructure/knowledge-base` |
|`/content/sys` | `/content/system` |
|`/content/sys/err` | `/content/system/errata` |
|`/content/sys/info` | `/content/system/information` |
|`/content/sys/kb` | `/content/system/knowledge-base` |

* Update most of the internal links according to new file structure and zola syntax.

### CODE REVIEW

**Comment by szclsya** [comment]
I think we can use a more descriptive naming scheme (for example, `developer` instead of `dev`), since these no longer serves as a prefix, so the added length should be okay.

**Comment by bobby285271** [comment]
> I think we can use a more descriptive naming scheme (for example, `developer` instead of `dev`). Since these no longer serves as a prefix, the added length should be okay.

Shall I rename the section directories as follows?

| Before | After |
|:---:|:---:|
|`/content/dev` | `/content/developer` |
|`/content/dev/sys` | `/content/developer/system` |
|`/content/infra` | `/content/infrastructure` |
|`/content/sys` | `/content/system` |
|`/content/sys/err` | `/content/system/errata` |
|`/content/sys/info` | `/content/system/information` |
|`/content/sys/kb` | `/content/system/knowledge-base` |

**Comment by szclsya** [comment]
That looks good enough for now. We can do some more fine-grained adjustments based on this later.

**Comment by bobby285271** [comment]
Ready for review. Note that most section folders are still missing `_index.md`.

**Comment by szclsya** [comment]
LGTM. Thank you!

**Pull request merged**
